# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c978c6b2e29d810088f3ac043dab96c53ebc9add46a662468bea831bd608598b093498002e4ca0ba36d9666d2a48d63abd2fc677d6ec1a12f36e884d484878e

test:
  secret_key_base: 64e9317ff1eaa9f1ca47a91dbe15e3dc5bda100aa2fcc5d39db06a14e9319aab329ae22e5dedf0ab1bfe491f2a978af0ec0c632758bc8729548ea32c017ca349

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
